# Generated by Django 3.0 on 2023-07-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='lastname',
            field=models.CharField(default='koutari', max_length=100),
        ),
    ]
