# Generated by Django 3.0 on 2023-07-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0002_car_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(default='koutari', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
