# Generated by Django 3.0 on 2023-07-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0003_auto_20230708_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('cin', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Conjoint',
            fields=[
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('cin', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaires.Beneficiaire')),
            ],
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id_enfant', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaires.Beneficiaire')),
            ],
        ),
        migrations.CreateModel(
            name='InformationOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pv', models.CharField(max_length=255)),
                ('operateur', models.CharField(max_length=255)),
                ('nom_operation', models.CharField(max_length=255)),
                ('num_ressencement', models.CharField(max_length=255)),
                ('date_ressencement', models.DateField()),
                ('date_affectation', models.DateField()),
                ('type_intervention', models.CharField(max_length=255)),
                ('prix_produit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subvention_fshiu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_demolition', models.DateField()),
                ('num_lot', models.CharField(max_length=255)),
                ('fichier_joint', models.FileField(upload_to='uploads/')),
                ('observation', models.TextField()),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaires.Beneficiaire')),
            ],
        ),
        migrations.CreateModel(
            name='OrigineBeneficiaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('douar', models.CharField(max_length=255)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaires.Beneficiaire')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('login', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('mot_de_passe', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
