# Generated by Django 3.0 on 2023-07-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0004_auto_20230708_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiaire',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='conjoint',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='enfant',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='informationoperation',
            options={'ordering': ['nom_operation']},
        ),
        migrations.AlterModelOptions(
            name='originebeneficiaire',
            options={'ordering': ['ville']},
        ),
    ]
