# Generated by Django 3.0 on 2023-07-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0005_auto_20230708_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='etat',
            field=models.CharField(default='etat', max_length=150),
        ),
    ]
