# Generated by Django 3.0 on 2023-07-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0006_enfant_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfant',
            name='etat',
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='etat',
            field=models.CharField(default='etat', max_length=150),
        ),
    ]
