# Generated by Django 3.0 on 2023-07-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0007_auto_20230709_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaire',
            name='etat',
        ),
    ]
