# Generated by Django 3.0 on 2023-07-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0008_remove_beneficiaire_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaire',
            name='etat',
            field=models.CharField(default='etat', max_length=150),
        ),
    ]
