# Generated by Django 3.0 on 2023-07-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0009_beneficiaire_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='etat',
            field=models.CharField(choices=[('valide', 'valide'), ('invalide', 'invalide')], max_length=150),
        ),
        migrations.AlterField(
            model_name='informationoperation',
            name='operateur',
            field=models.CharField(choices=[('Alomrane', 'Alomrane')], max_length=255),
        ),
        migrations.AlterField(
            model_name='informationoperation',
            name='type_intervention',
            field=models.CharField(choices=[('type1', 'type1'), ('type2', 'type2')], max_length=255),
        ),
        migrations.AlterField(
            model_name='originebeneficiaire',
            name='commune',
            field=models.CharField(choices=[('commune_Settat', 'commune_Settat')], max_length=255),
        ),
        migrations.AlterField(
            model_name='originebeneficiaire',
            name='douar',
            field=models.CharField(choices=[('kilaz', 'kilaz')], max_length=255),
        ),
        migrations.AlterField(
            model_name='originebeneficiaire',
            name='ville',
            field=models.CharField(choices=[('Settat', 'Settat')], max_length=255),
        ),
    ]
