# Generated by Django 3.0 on 2023-07-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0010_auto_20230712_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaire',
            name='etat',
        ),
    ]
